// Read-only postflight; reports only booleans/counts/hashes, never row contents or secrets.
import {spawnSync} from 'node:child_process';
import {writeFileSync} from 'node:fs';
const script = "import json,hashlib,sqlite3,re\nfrom pathlib import Path\nroot=Path(\"/home/nekohost/services/Mini-Server-Web-EqMgmt\")\nrelease=Path(\"/home/nekohost/.local/share/mini-server-eqmgmt/releases/ui-portrait-correction-20260914T045732Z\")\ninitial=Path(\"/home/nekohost/.local/share/mini-server-eqmgmt/releases/ui-navigation-search-20260914T045012Z\")\nresult=json.loads((release/\"result.json\").read_text())\nfirst=json.loads((initial/\"result.json\").read_text())\nfiles=dict(first[\"files\"],**result[\"files\"])\nproc=Path(\"/proc/\"+str(result[\"new_pid\"]))\nlive=sqlite3.connect(root.joinpath(\"equipment.db\").as_uri()+\"?mode=ro\",uri=True)\nold=sqlite3.connect(initial.joinpath(\"equipment-before.db\").as_uri()+\"?mode=ro\",uri=True)\ntables=(\"equipments\",\"equipment_options\",\"lineup_nodes\")\nsame={name: live.execute(\"SELECT * FROM \"+name+\" ORDER BY 1\").fetchall()==old.execute(\"SELECT * FROM \"+name+\" ORDER BY 1\").fetchall() for name in tables}\nsafe_columns=\"UserId,LoginId,Role,Password,Name,NickName,Email\"\nidentity_same=live.execute(\"SELECT \"+safe_columns+\" FROM users ORDER BY UserId\").fetchall()==old.execute(\"SELECT \"+safe_columns+\" FROM users ORDER BY UserId\").fetchall()\nbefore={row[0]:json.loads(row[1] or \"{}\") for row in old.execute(\"SELECT UserId,PreferencesJSON FROM user_settings\")}\nafter={row[0]:json.loads(row[1] or \"{}\") for row in live.execute(\"SELECT UserId,PreferencesJSON FROM user_settings\")}\ndef effective(v):\n    return dict(v,theme=v.get(\"theme\",\"system\"),layout_skin=v.get(\"layout_skin\",\"standard\"),deadline_email_opt_in=v.get(\"deadline_email_opt_in\",False))\nsame_settings=all(effective(before.get(uid,{}))==effective(after.get(uid,{})) for uid in before.keys()|after.keys())\nchecks={\"pid\":result[\"new_pid\"],\"cwd_matches\":proc.joinpath(\"cwd\").resolve()==root,\n\"files_match\":all(hashlib.sha256(root.joinpath(name).read_bytes()).hexdigest()==hashes[\"after\"] for name,hashes in files.items()),\n\"integrity\":live.execute(\"PRAGMA integrity_check\").fetchone()[0],\n\"foreign_key_violations\":len(live.execute(\"PRAGMA foreign_key_check\").fetchall()),\n\"business_rows_identical\":same,\"user_identity_role_password_unchanged\":identity_same,\n\"all_users_effective_preferences_restored\":same_settings,\n\"startup_error_markers\":len(re.findall(r\"Traceback|ERROR|Fatal\",release.joinpath(\"service-start.log\").read_text()))}\nchecks[\"file_count\"]=len(files)\nprint(json.dumps({\"postflight\":checks,\"initial_deployment\":first,\"portrait_deployment\":result}))\n";
const quote = s => "'" + s.replaceAll("'", "'\\''") + "'";
const result = spawnSync('ssh', ['-o','BatchMode=yes','-o','ConnectTimeout=8','eqmgmt-backup',
    '/home/nekohost/services/Mini-Server-Web-EqMgmt/.venv/bin/python -c ' + quote(script)],
    {encoding:'utf8',timeout:20000});
if(result.status !== 0) throw new Error('Postflight failed: ' + (result.stderr || result.error));
const evidence = JSON.parse(result.stdout);
writeFileSync(new URL('postflight.json',import.meta.url), JSON.stringify(evidence,null,2)+'\n');
console.log(JSON.stringify(evidence.postflight));
